// proto/message.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.20.3
// source: message.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{0}
}

func (x *NodeInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NodeInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NodeList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeList) Reset() {
	*x = NodeList{}
	mi := &file_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeList) ProtoMessage() {}

func (x *NodeList) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeList.ProtoReflect.Descriptor instead.
func (*NodeList) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{2}
}

func (x *NodeList) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{3}
}

type Signal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=Term,proto3" json:"Term,omitempty"`
	Flag          bool                   `protobuf:"varint,2,opt,name=flag,proto3" json:"flag,omitempty"`
	Ind           int32                  `protobuf:"varint,3,opt,name=ind,proto3" json:"ind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{4}
}

func (x *Signal) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *Signal) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *Signal) GetInd() int32 {
	if x != nil {
		return x.Ind
	}
	return 0
}

type RequestVoteArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	Addr          string                 `protobuf:"bytes,5,opt,name=Addr,proto3" json:"Addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteArgs) Reset() {
	*x = RequestVoteArgs{}
	mi := &file_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteArgs) ProtoMessage() {}

func (x *RequestVoteArgs) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteArgs.ProtoReflect.Descriptor instead.
func (*RequestVoteArgs) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{5}
}

func (x *RequestVoteArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RequestVoteArgs) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteArgs) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type RequestVoteReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VoteGranted   bool                   `protobuf:"varint,1,opt,name=vote_granted,json=voteGranted,proto3" json:"vote_granted,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	VotedFor      string                 `protobuf:"bytes,3,opt,name=votedFor,proto3" json:"votedFor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReply) Reset() {
	*x = RequestVoteReply{}
	mi := &file_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReply) ProtoMessage() {}

func (x *RequestVoteReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReply.ProtoReflect.Descriptor instead.
func (*RequestVoteReply) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{6}
}

func (x *RequestVoteReply) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *RequestVoteReply) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReply) GetVotedFor() string {
	if x != nil {
		return x.VotedFor
	}
	return ""
}

type HearBeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=Term,proto3" json:"Term,omitempty"`
	LogInd        int32                  `protobuf:"varint,3,opt,name=LogInd,proto3" json:"LogInd,omitempty"`
	Add           string                 `protobuf:"bytes,4,opt,name=Add,proto3" json:"Add,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HearBeatRequest) Reset() {
	*x = HearBeatRequest{}
	mi := &file_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HearBeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HearBeatRequest) ProtoMessage() {}

func (x *HearBeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HearBeatRequest.ProtoReflect.Descriptor instead.
func (*HearBeatRequest) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{7}
}

func (x *HearBeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HearBeatRequest) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *HearBeatRequest) GetLogInd() int32 {
	if x != nil {
		return x.LogInd
	}
	return 0
}

func (x *HearBeatRequest) GetAdd() string {
	if x != nil {
		return x.Add
	}
	return ""
}

type HearBeatReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          bool                   `protobuf:"varint,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	NewLeader     bool                   `protobuf:"varint,2,opt,name=NewLeader,proto3" json:"NewLeader,omitempty"`
	Term          int32                  `protobuf:"varint,3,opt,name=Term,proto3" json:"Term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HearBeatReply) Reset() {
	*x = HearBeatReply{}
	mi := &file_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HearBeatReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HearBeatReply) ProtoMessage() {}

func (x *HearBeatReply) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HearBeatReply.ProtoReflect.Descriptor instead.
func (*HearBeatReply) Descriptor() ([]byte, []int) {
	return file_message_proto_rawDescGZIP(), []int{8}
}

func (x *HearBeatReply) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

func (x *HearBeatReply) GetNewLeader() bool {
	if x != nil {
		return x.NewLeader
	}
	return false
}

func (x *HearBeatReply) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

var File_message_proto protoreflect.FileDescriptor

const file_message_proto_rawDesc = "" +
	"\n" +
	"\rmessage.proto\x12\araft_pb\".\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\",\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"3\n" +
	"\bNodeList\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.raft_pb.NodeInfoR\x05nodes\"\a\n" +
	"\x05Empty\"B\n" +
	"\x06Signal\x12\x12\n" +
	"\x04Term\x18\x01 \x01(\x05R\x04Term\x12\x12\n" +
	"\x04flag\x18\x02 \x01(\bR\x04flag\x12\x10\n" +
	"\x03ind\x18\x03 \x01(\x05R\x03ind\"I\n" +
	"\x0fRequestVoteArgs\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Term\x18\x02 \x01(\x05R\x04Term\x12\x12\n" +
	"\x04Addr\x18\x05 \x01(\tR\x04Addr\"e\n" +
	"\x10RequestVoteReply\x12!\n" +
	"\fvote_granted\x18\x01 \x01(\bR\vvoteGranted\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12\x1a\n" +
	"\bvotedFor\x18\x03 \x01(\tR\bvotedFor\"_\n" +
	"\x0fHearBeatRequest\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Term\x18\x02 \x01(\x05R\x04Term\x12\x16\n" +
	"\x06LogInd\x18\x03 \x01(\x05R\x06LogInd\x12\x10\n" +
	"\x03Add\x18\x04 \x01(\tR\x03Add\"U\n" +
	"\rHearBeatReply\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\bR\x04Flag\x12\x1c\n" +
	"\tNewLeader\x18\x02 \x01(\bR\tNewLeader\x12\x12\n" +
	"\x04Term\x18\x03 \x01(\x05R\x04Term2\xff\x02\n" +
	"\x10NodeRegistration\x12<\n" +
	"\fRegisterNode\x12\x11.raft_pb.NodeInfo\x1a\x19.raft_pb.RegisterResponse\x12-\n" +
	"\bGetNodes\x12\x0e.raft_pb.Empty\x1a\x11.raft_pb.NodeList\x12A\n" +
	"\rSendHeartBeat\x12\x18.raft_pb.HearBeatRequest\x1a\x16.raft_pb.HearBeatReply\x12B\n" +
	"\vRequestVote\x12\x18.raft_pb.RequestVoteArgs\x1a\x19.raft_pb.RequestVoteReply\x12@\n" +
	"\x10RemoveConnection\x12\x11.raft_pb.NodeInfo\x1a\x19.raft_pb.RegisterResponse\x125\n" +
	"\bcheckRPC\x12\x0e.raft_pb.Empty\x1a\x19.raft_pb.RegisterResponseB\tZ\a./protob\x06proto3"

var (
	file_message_proto_rawDescOnce sync.Once
	file_message_proto_rawDescData []byte
)

func file_message_proto_rawDescGZIP() []byte {
	file_message_proto_rawDescOnce.Do(func() {
		file_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)))
	})
	return file_message_proto_rawDescData
}

var file_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_message_proto_goTypes = []any{
	(*NodeInfo)(nil),         // 0: raft_pb.NodeInfo
	(*RegisterResponse)(nil), // 1: raft_pb.RegisterResponse
	(*NodeList)(nil),         // 2: raft_pb.NodeList
	(*Empty)(nil),            // 3: raft_pb.Empty
	(*Signal)(nil),           // 4: raft_pb.Signal
	(*RequestVoteArgs)(nil),  // 5: raft_pb.RequestVoteArgs
	(*RequestVoteReply)(nil), // 6: raft_pb.RequestVoteReply
	(*HearBeatRequest)(nil),  // 7: raft_pb.HearBeatRequest
	(*HearBeatReply)(nil),    // 8: raft_pb.HearBeatReply
}
var file_message_proto_depIdxs = []int32{
	0, // 0: raft_pb.NodeList.nodes:type_name -> raft_pb.NodeInfo
	0, // 1: raft_pb.NodeRegistration.RegisterNode:input_type -> raft_pb.NodeInfo
	3, // 2: raft_pb.NodeRegistration.GetNodes:input_type -> raft_pb.Empty
	7, // 3: raft_pb.NodeRegistration.SendHeartBeat:input_type -> raft_pb.HearBeatRequest
	5, // 4: raft_pb.NodeRegistration.RequestVote:input_type -> raft_pb.RequestVoteArgs
	0, // 5: raft_pb.NodeRegistration.RemoveConnection:input_type -> raft_pb.NodeInfo
	3, // 6: raft_pb.NodeRegistration.checkRPC:input_type -> raft_pb.Empty
	1, // 7: raft_pb.NodeRegistration.RegisterNode:output_type -> raft_pb.RegisterResponse
	2, // 8: raft_pb.NodeRegistration.GetNodes:output_type -> raft_pb.NodeList
	8, // 9: raft_pb.NodeRegistration.SendHeartBeat:output_type -> raft_pb.HearBeatReply
	6, // 10: raft_pb.NodeRegistration.RequestVote:output_type -> raft_pb.RequestVoteReply
	1, // 11: raft_pb.NodeRegistration.RemoveConnection:output_type -> raft_pb.RegisterResponse
	1, // 12: raft_pb.NodeRegistration.checkRPC:output_type -> raft_pb.RegisterResponse
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_message_proto_init() }
func file_message_proto_init() {
	if File_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_proto_rawDesc), len(file_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_message_proto_goTypes,
		DependencyIndexes: file_message_proto_depIdxs,
		MessageInfos:      file_message_proto_msgTypes,
	}.Build()
	File_message_proto = out.File
	file_message_proto_goTypes = nil
	file_message_proto_depIdxs = nil
}
